"""initial_migration

Revision ID: 77fc2409b0ef
Revises:
Create Date: 2025-01-06 10:24:53.868300

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "77fc2409b0ef"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decision",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True
        ),
        sa.Column(
            "modified_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True
        ),
        sa.Column("child_full_name", sa.String(length=100), nullable=False),
        sa.Column("child_full_name_gen", sa.String(length=100), nullable=False),
        sa.Column("child_address", sa.String(length=1024), nullable=False),
        sa.Column("child_town", sa.String(length=128), nullable=False),
        sa.Column("child_postal_code", sa.String(length=12), nullable=True),
        sa.Column("child_post", sa.String(length=12), nullable=True),
        sa.Column("child_pesel", sa.String(length=12), nullable=False),
        sa.Column("child_birth_date", sa.Date(), nullable=False),
        sa.Column("child_birth_place", sa.String(length=100), nullable=False),
        sa.Column("child_student", sa.Boolean(), nullable=False),
        sa.Column("klass", sa.String(length=30), nullable=True),
        sa.Column("profession", sa.String(length=120), nullable=True),
        sa.Column("school_parent_organisation", sa.String(length=512), nullable=True),
        sa.Column("school_type", sa.String(length=50), nullable=False),
        sa.Column("school_name", sa.String(length=1024), nullable=False),
        sa.Column("school_address", sa.String(length=1024), nullable=False),
        sa.Column("school_town", sa.String(length=128), nullable=False),
        sa.Column("school_postal_code", sa.String(length=12), nullable=False),
        sa.Column("school_post", sa.String(length=128), nullable=False),
        sa.Column("address_child_checkbox", sa.Boolean(), nullable=False),
        sa.Column("address_first_parent_checkbox", sa.Boolean(), nullable=False),
        sa.Column("first_parent_full_name", sa.String(length=100), nullable=False),
        sa.Column("first_parent_full_name_gen", sa.String(length=100), nullable=False),
        sa.Column("first_parent_address", sa.String(length=1024), nullable=False),
        sa.Column("first_parent_town", sa.String(length=128), nullable=False),
        sa.Column("first_parent_post", sa.String(length=128), nullable=True),
        sa.Column("first_parent_postal_code", sa.String(length=12), nullable=True),
        sa.Column("second_parent_full_name", sa.String(length=100), nullable=True),
        sa.Column("second_parent_full_name_gen", sa.String(length=100), nullable=True),
        sa.Column("second_parent_address", sa.String(length=1024), nullable=True),
        sa.Column("second_parent_town", sa.String(length=128), nullable=True),
        sa.Column("second_parent_postal_code", sa.String(length=12), nullable=True),
        sa.Column("second_parent_post", sa.String(length=128), nullable=True),
        sa.Column("support_center_name_nominative", sa.String(length=1024), nullable=True),
        sa.Column("support_center_name_genitive", sa.String(length=1024), nullable=True),
        sa.Column("support_center_institute_name", sa.String(length=1024), nullable=True),
        sa.Column("support_center_kurator", sa.String(length=1024), nullable=True),
        sa.Column("support_center_address", sa.String(length=1024), nullable=True),
        sa.Column("support_center_town", sa.String(length=128), nullable=True),
        sa.Column("support_center_postal_code", sa.String(length=12), nullable=True),
        sa.Column("support_center_post", sa.String(length=128), nullable=True),
        sa.Column("issue", sa.String(length=256), nullable=False),
        sa.Column("period", sa.String(length=256), nullable=False),
        sa.Column("reasons", sqlite.JSON(), nullable=False),
        sa.Column("activity_form", sa.String(length=20), nullable=True),
        sa.Column("decision_no", sa.String(length=15), nullable=False),
        sa.Column("application_date", sa.Date(), nullable=False),
        sa.Column("meeting_date", sa.Date(), nullable=False),
        sa.Column("meeting_time", sa.String(length=50), nullable=False),
        sa.Column("meeting_members", sqlite.JSON(), nullable=False),
        sa.Column("file_no", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "school",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("rspo_id", sa.Integer(), nullable=True),
        sa.Column("rspo_type_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("parent_organisation_name", sa.String(length=512), nullable=True),
        sa.Column("name", sa.String(length=1024), nullable=False),
        sa.Column("address", sa.String(length=1024), nullable=False),
        sa.Column("town", sa.String(length=128), nullable=False),
        sa.Column("postal_code", sa.String(length=12), nullable=False),
        sa.Column("post", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "support_center",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("district_id", sa.Integer(), nullable=True),
        sa.Column("province_id", sa.Integer(), nullable=True),
        sa.Column("rspo", sa.Integer(), nullable=True),
        sa.Column("name_nominative", sa.String(length=1024), nullable=False),
        sa.Column("name_itive", sa.String(length=1024), nullable=False),
        sa.Column("institute_name", sa.String(length=1024), nullable=False),
        sa.Column("kurator", sa.String(length=1024), nullable=False),
        sa.Column("address", sa.String(length=1024), nullable=False),
        sa.Column("town", sa.String(length=128), nullable=False),
        sa.Column("postal_code", sa.String(length=12), nullable=False),
        sa.Column("post", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("support_center")
    op.drop_table("school")
    op.drop_table("decision")
    # ### end Alembic commands ###
